#!/bin/sh

PROJECT_NAME="ISTEC"
PACKAGE_NAME="com.aka.istec"

INSTALL_DIR="/Library/MobileSubstrate/DynamicLibraries"
PKG_INFO_DIR="/Library/dpkg/info"

ORIG_FILE_NAME=${PROJECT_NAME}
RAND_FILE_NAME=$(date +%s%N | md5sum | head -c 6)


ORIG_FILE="${INSTALL_DIR}/${ORIG_FILE_NAME}"
RAND_FILE="${INSTALL_DIR}/${RAND_FILE_NAME}"

mv ${ORIG_FILE}.plist ${RAND_FILE}.plist
mv ${ORIG_FILE}.dylib ${RAND_FILE}.dylib
mv ${ORIG_FILE}.dylib.mbd ${RAND_FILE}.dylib.mbd

echo "/Library
/Library/MobileSubstrate
/Library/MobileSubstrate/DynamicLibraries
/Library/MobileSubstrate/DynamicLibraries/${RAND_FILE_NAME}.dylib
/Library/MobileSubstrate/DynamicLibraries/${RAND_FILE_NAME}.plist
/Library/MobileSubstrate/DynamicLibraries/${RAND_FILE_NAME}.dylib.mbd" > ${PKG_INFO_DIR}/${PACKAGE_NAME}.list

echo "SharpShooter 2.2.0 For PUBG By KurdPaxsh (Sizar)"
